# Site settings
title: Dev
header-img: img/home-bg.png
email: vcorvington@gmail.com
copyright_name: vcorvington
description: > # this means to ignore newlines until "baseurl:"
  A Memoir
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: vcorvington
github_username:  vcorvington
learn_profile: vcorvington
email_username: vcorvington@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
